
import duckdb
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

# --- CONFIGURATION ---
DB_PATH = 'knust_engineering_new.duckdb'
REPORT_TITLE = "KNUST Engineering Data Analysis Report"
OUTPUT_FILE = "KNUST_Comprehensive_Report.docx"

# --- HELPER FUNCTIONS ---
def add_heading(doc, text, level=1):
    doc.add_heading(text, level=level)

def add_paragraph(doc, text):
    doc.add_paragraph(text)

def add_df_table(doc, df):
    if df.empty:
        doc.add_paragraph("(No data available)")
        return
    
    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = 'Light Shading Accent 1'
    
    # Header
    hdr_cells = table.rows[0].cells
    for i, col_name in enumerate(df.columns):
        hdr_cells[i].text = str(col_name)
    
    # Rows
    for index, row in df.iterrows():
        row_cells = table.add_row().cells
        for i, item in enumerate(row):
            if isinstance(item, float):
                row_cells[i].text = f"{item:.2f}"
            else:
                row_cells[i].text = str(item)

def get_con():
    return duckdb.connect(DB_PATH, read_only=True)

# --- MAIN GENERATION LOGIC ---
def generate_report():
    con = get_con()
    doc = Document()
    
    # 0. Title Page
    title = doc.add_heading(REPORT_TITLE, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}")
    doc.add_paragraph("Generated by: Antigravity AI Assistant")
    doc.add_page_break()

    # 1. HIERARCHY ANALYSIS
    add_heading(doc, "1. Hierarchy Analysis", level=1)
    add_paragraph(doc, "Overview of student performance trends across College, Faculty, and Department levels.")
    
    # College Level
    add_heading(doc, "1.1 College-Wide Performance Trend", level=2)
    q_college = """
        SELECT academic_year, AVG(mark) as avg_mark, COUNT(*) as records
        FROM student_performance
        GROUP BY academic_year
        ORDER BY academic_year
    """
    df_college = con.execute(q_college).df()
    add_df_table(doc, df_college)
    
    # Faculty Level
    add_heading(doc, "1.2 Faculty Performance (Average Mark per Year)", level=2)
    q_faculty = """
        SELECT academic_year, faculty, AVG(avg_mark) as avg_mark
        FROM course_summary
        GROUP BY academic_year, faculty
        ORDER BY academic_year, faculty
    """
    df_faculty = con.execute(q_faculty).df()
    # Pivot for better readability? Simple table for now.
    add_df_table(doc, df_faculty.head(10)) # Limit for brevity in doc, or show full? Let's show filtered recent years if too long.
    
    # Department Level (Snapshot 2020/2021)
    add_heading(doc, "1.3 Department Performance (Snapshot: 2020/2021)", level=2)
    q_dept = """
        SELECT department, AVG(avg_mark) as mean_mark
        FROM course_summary
        WHERE academic_year = '2020/2021'
        GROUP BY department
        ORDER BY mean_mark DESC
    """
    df_dept = con.execute(q_dept).df()
    add_df_table(doc, df_dept)

    # 2. COURSE PERFORMANCE
    add_heading(doc, "2. Course Performance Analysis", level=1)
    
    # High Performers
    add_heading(doc, "2.1 All-Time Highest Performing Courses", level=2)
    q_high = """
        SELECT REPLACE(course_code, '\n', ' ') as code, MAX(course_name) as name, AVG(avg_mark) as all_time_avg
        FROM course_summary
        GROUP BY code
        HAVING COUNT(*) > 3
        ORDER BY all_time_avg DESC
        LIMIT 10
    """
    df_high = con.execute(q_high).df()
    add_df_table(doc, df_high)

    # Low Performers
    add_heading(doc, "2.2 All-Time Lowest Performing Courses", level=2)
    q_low = """
        SELECT REPLACE(course_code, '\n', ' ') as code, MAX(course_name) as name, AVG(avg_mark) as all_time_avg
        FROM course_summary
        GROUP BY code
        HAVING COUNT(*) > 3
        ORDER BY all_time_avg ASC
        LIMIT 10
    """
    df_low = con.execute(q_low).df()
    add_df_table(doc, df_low)
    
    # 3. COHORT ANALYSIS (Focus: 2018/2019)
    add_heading(doc, "3. Cohort Analysis (Focus: Class of 2018/2019)", level=1)
    add_paragraph(doc, "Deep dive into the 2018/2019 cohort, analyzing the best and least performing students and the courses impacting them.")
    
    target_cohort = '2018/2019'
    final_year = '2021/2022' # Start + 3
    
    # Top 10
    add_heading(doc, f"3.1 Top 10 Graduates (Class of {target_cohort})", level=2)
    q_top10 = f"""
        WITH start_cohort AS (
            SELECT DISTINCT student_id 
            FROM student_performance 
            WHERE academic_year = '{target_cohort}' AND level = 1
        ),
        final_perf AS (
            SELECT sp.student_id, sp.cwa, sp.program
            FROM student_performance sp
            JOIN start_cohort sc ON sp.student_id = sc.student_id
            WHERE sp.academic_year = '{final_year}' AND sp.level = 4 AND sp.semester = 2
            AND sp.cwa > 0 AND sp.status NOT IN ('Deferred', 'Withdrawn')
        )
        SELECT student_id, MAX(cwa) as Final_CWA, MAX(program) as Program
        FROM final_perf
        GROUP BY student_id
        ORDER BY Final_CWA DESC
        LIMIT 10
    """
    df_top = con.execute(q_top10).df()
    add_df_table(doc, df_top)
    
    # Bottom 10
    add_heading(doc, f"3.2 Bottom 10 Graduates (Class of {target_cohort})", level=2)
    q_bot10 = f"""
        WITH start_cohort AS (
            SELECT DISTINCT student_id 
            FROM student_performance 
            WHERE academic_year = '{target_cohort}' AND level = 1
        ),
        final_perf AS (
            SELECT sp.student_id, sp.cwa, sp.program
            FROM student_performance sp
            JOIN start_cohort sc ON sp.student_id = sc.student_id
            WHERE sp.academic_year = '{final_year}' AND sp.level = 4 AND sp.semester = 2
            AND sp.cwa > 0 AND sp.status NOT IN ('Deferred', 'Withdrawn')
        )
        SELECT student_id, MAX(cwa) as Final_CWA, MAX(program) as Program
        FROM final_perf
        GROUP BY student_id
        ORDER BY Final_CWA ASC
        LIMIT 10
    """
    df_bot = con.execute(q_bot10).df()
    add_df_table(doc, df_bot)
    
    # Impact Analysis function
    def get_impact(ids, order_desc=True):
        if not ids: return pd.DataFrame()
        ids_str = ",".join([f"'{s}'" for s in ids])
        sort_order = "DESC" if order_desc else "ASC"
        q = f"""
            SELECT sp.course_code, MAX(cs.course_name) as course_name, AVG(sp.mark) as avg_mark
            FROM student_performance sp
            LEFT JOIN (
                SELECT REPLACE(course_code, '\n', ' ') as clean_code, MAX(course_name) as course_name 
                FROM course_summary GROUP BY clean_code
            ) cs ON REPLACE(sp.course_code, '\n', ' ') = cs.clean_code
            WHERE sp.student_id IN ({ids_str})
            GROUP BY sp.course_code
            HAVING COUNT(*) > 1
            ORDER BY avg_mark {sort_order}
            LIMIT 5
        """
        return con.execute(q).df()

    # Top 10 - Strongest Courses
    if not df_top.empty:
        add_heading(doc, "3.3 Top 10 Group: Strongest Courses (Boosters)", level=2)
        df_boost_top = get_impact(df_top['student_id'].tolist(), order_desc=True)
        add_df_table(doc, df_boost_top)

    # Bottom 10 - Weakest Courses
    if not df_bot.empty:
        add_heading(doc, "3.4 Bottom 10 Group: Weakest Courses (Draggers)", level=2)
        df_drag_bot = get_impact(df_bot['student_id'].tolist(), order_desc=False)
        add_df_table(doc, df_drag_bot)

    # 4. RETENTION & ATTRITION
    add_heading(doc, "4. Retention & Attrition", level=1)
    
    add_heading(doc, "4.1 Failure/Trail Rates per Year", level=2)
    q_risk = """
        SELECT academic_year, 
               (SUM(num_trailed) * 100.0 / NULLIF(SUM(num_trailed + num_passed), 0)) as failure_rate
        FROM course_summary 
        GROUP BY academic_year
        ORDER BY academic_year
    """
    df_risk = con.execute(q_risk).df()
    add_df_table(doc, df_risk)

    # 5. DEMOGRAPHICS
    add_heading(doc, "5. Demographics Analysis", level=1)
    add_heading(doc, "5.1 Gender Performance Gap (Overall)", level=2)
    q_gen = """
        SELECT gender, AVG(mark) as avg_mark, AVG(cwa) as avg_cwa, COUNT(*) as records
        FROM student_performance
        WHERE gender IN ('Male', 'Female')
        GROUP BY gender
    """
    df_gen = con.execute(q_gen).df()
    add_df_table(doc, df_gen)

    # 6. SEMESTER ANALYSIS
    add_heading(doc, "6. Semester Analysis", level=1)
    add_heading(doc, "6.1 Performance by Semester (1-8)", level=2)
    q_sem = """
        SELECT semester, AVG(mark) as avg_mark
        FROM student_performance
        WHERE semester <= 8
        GROUP BY semester
        ORDER BY semester
    """
    df_sem = con.execute(q_sem).df()
    add_df_table(doc, df_sem)

    # Save
    doc.save(OUTPUT_FILE)
    print(f"Report generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_report()
