import duckdb
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

# 1. CONNECT TO DATA
con = duckdb.connect('knust_engineering_new.duckdb', read_only=True)

# 2. FETCH DATA
# Summary
q_summary = "SELECT COUNT(DISTINCT student_id), COUNT(DISTINCT course_code) FROM student_performance"
res_sum = con.execute(q_summary).fetchone()
total_students, total_courses = res_sum[0], res_sum[1]

# Trends
q_trend = "SELECT academic_year, AVG(mark) as avg_mark FROM student_performance GROUP BY academic_year ORDER BY academic_year"
df_trend = con.execute(q_trend).df()
latest_avg = df_trend.iloc[-1]['avg_mark']
peak_avg = df_trend['avg_mark'].max()
peak_year = df_trend.loc[df_trend['avg_mark'].idxmax()]['academic_year']

# Hardest Courses
q_diff = """
    SELECT course_code, course_name, 
           AVG((num_passed * 100.0) / NULLIF((num_passed + num_trailed), 0)) as pass_rate
    FROM course_summary
    GROUP BY course_code, course_name
    HAVING COUNT(*) > 5
    ORDER BY pass_rate ASC
    LIMIT 5
"""
df_diff = con.execute(q_diff).df()

# Failure Rates
q_risk = """
    SELECT academic_year, 
           (SUM(num_trailed) * 100.0 / NULLIF(SUM(num_trailed + num_passed), 0)) as failure_rate
    FROM course_summary 
    GROUP BY academic_year
    ORDER BY academic_year
"""
df_risk = con.execute(q_risk).df()
latest_fail = df_risk.iloc[-1]['failure_rate']
start_fail = df_risk.iloc[0]['failure_rate']

# 3. CREATE DOCUMENT
doc = Document()

# Styles
style = doc.styles['Normal']
style.font.name = 'Calibri'
style.font.size = Pt(11)

# Title
title = doc.add_heading('KNUST Engineering Data Analysis Report', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}")
doc.add_paragraph(f"Generated by: AI Assistant")
doc.add_paragraph("")

# Executive Summary
doc.add_heading('1. Executive Summary', level=1)
summary_text = (
    f"This report provides a comprehensive analysis of student performance data for the College of Engineering. "
    f"The dataset covers {len(df_trend)} academic years, involving {total_students:,} distinct students and {total_courses} courses.\n\n"
    f"Key observations include a stable average performance across the years, but a concerning upward trend in failure rates "
    f"in recent academic sessions. Specific courses have been identified as significant hurdles for student progression."
)
doc.add_paragraph(summary_text)

# Section 2: Trends
doc.add_heading('2. Academic Performance Trends', level=1)
doc.add_paragraph(
    f"The overall academic performance has remained relatively stable. "
    f"The highest average mark of {peak_avg:.2f} was recorded in {peak_year}. "
    f"However, the most recent academic year ({df_trend.iloc[-1]['academic_year']}) shows an average mark of {latest_avg:.2f}, "
    f"which is slightly below the peak."
)

# Table for Trends
table = doc.add_table(rows=1, cols=2)
table.style = 'Light Shading Accent 1'
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Academic Year'
hdr_cells[1].text = 'Average Mark'

for index, row in df_trend.iterrows():
    row_cells = table.add_row().cells
    row_cells[0].text = str(row['academic_year'])
    row_cells[1].text = f"{row['avg_mark']:.2f}"

doc.add_paragraph("")

# Section 3: Critical Course Analysis
doc.add_heading('3. Critical Course Analysis', level=1)
doc.add_paragraph(
    "The analysis identified the following courses as having the lowest pass rates, representing significant academic hurdles:"
)

# Table for Hardest Courses
table2 = doc.add_table(rows=1, cols=3)
table2.style = 'Light Shading Accent 2'
hdr_cells2 = table2.rows[0].cells
hdr_cells2[0].text = 'Course Code'
hdr_cells2[1].text = 'Course Name'
hdr_cells2[2].text = 'Pass Rate (%)'

for index, row in df_diff.iterrows():
    row_cells = table2.add_row().cells
    row_cells[0].text = str(row['course_code'])
    row_cells[1].text = str(row['course_name'])
    row_cells[2].text = f"{row['pass_rate']:.1f}%"

doc.add_paragraph("")
doc.add_paragraph(
    f"Recommendation: A targeted review of the curriculum and teaching methods for {df_diff.iloc[0]['course_code']} "
    f"({df_diff.iloc[0]['course_name']}) is highly recommended given its low pass rate of {df_diff.iloc[0]['pass_rate']:.1f}%."
)

# Section 4: Retention & Attrition Risks
doc.add_heading('4. Retention & Attrition Risks', level=1)
fail_trend_desc = "increasing" if latest_fail > start_fail else "decreasing"
doc.add_paragraph(
    f"Analysis of trail/failure rates indicates an {fail_trend_desc} trend. "
    f"The failure rate (proxy via trailed courses) has moved from {start_fail:.2f}% in {df_risk.iloc[0]['academic_year']} "
    f"to {latest_fail:.2f}% in {df_risk.iloc[-1]['academic_year']}."
)

# Table for Risk
table3 = doc.add_table(rows=1, cols=2)
table3.style = 'Light Shading Accent 3'
hdr_cells3 = table3.rows[0].cells
hdr_cells3[0].text = 'Academic Year'
hdr_cells3[1].text = 'Failure/Trail Rate (%)'

for index, row in df_risk.iterrows():
    row_cells = table3.add_row().cells
    row_cells[0].text = str(row['academic_year'])
    row_cells[1].text = f"{row['failure_rate']:.2f}%"

doc.add_paragraph("")

# Section 5: Conclusion
doc.add_heading('5. Conclusion', level=1)
doc.add_paragraph(
    "While the College of Engineering maintains a robust academic standard, the rising failure rates in recent years warrant further investigation. "
    "Interventions focused on high-risk courses and early identification of struggling students could help reverse this trend."
)

# SAVE
output_path = 'KNUST_Engineering_Data_Report.docx'
doc.save(output_path)
print(f"Report generated successfully: {output_path}")
